.equ CLEAR $93
.equ LF $0A
.equ CR $0D
.equ r0 $02
.equ r1 $04
.equ r2 $06
.equ r3 $08
.equ r4 $0A
.equ r5 $0C
.equ getc $9D00
.equ GETIN getc
.equ putc $9D03
.equ CHROUT putc
.equ exec $9D06
.equ print_str $9D09
.equ PRINT_STR print_str
.equ get_console_info $9DB4
.equ set_console_mode $9DB7
.equ set_stdin_read_mode $9DBA
.equ get_process_info $9D0C
.equ get_args $9D0F
.equ get_process_name $9D12
.equ active_table_lookup $9DA5
.equ parse_num $9D15
.equ bin_to_bcd16 $9D99
.equ hex_num_to_string $9D18
.equ GET_HEX_NUM hex_num_to_string
.equ kill_process $9D1B
.equ open_file $9D1E
.equ close_file $9D21
.equ read_file $9D24
.equ write_file $9D27
.equ seek_file $9DC0
.equ tell_file $9DC3
.equ load_dir_listing_extmem $9D2A
.equ get_pwd $9D2D
.equ chdir $9D30
.equ move_fd $9D9C
.equ copy_fd $9DA8
.equ pipe $9DBD
.equ res_extmem_bank $9D33
.equ free_extmem_bank $9D42
.equ share_extmem_bank $9D4B
.equ set_extmem_wbank $9D57
.equ set_extmem_rbank $9D36
.equ set_extmem_rptr $9D39
.equ set_extmem_wptr $9D3C
.equ readf_byte_extmem_y $9D3F
.equ writef_byte_extmem_y $9D48
.equ vread_byte_extmem_y $9D45
.equ vwrite_byte_extmem_y $9D4E
.equ pread_extmem_xy $9DAE
.equ pwrite_extmem_xy $9DB1
.equ memmove_extmem $9D51
.equ fill_extmem $9D54
.equ wait_process $9D5D
.equ fgetc $9D60
.equ fputc $9D63
.equ unlink $9D66
.equ rename $9D69
.equ copy_file $9D6C
.equ mkdir $9D6F
.equ rmdir $9D72
.equ get_time $9D9F
.equ get_sys_info $9DAB
.equ setup_chrout_hook $9D75
.equ release_chrout_hook $9D78
.equ send_byte_chrout_hook $9D87
.equ lock_vera_regs $9D93
.equ unlock_vera_regs $9D96
.equ setup_general_hook $9D7B
.equ release_general_hook $9D7E
.equ get_general_hook_info $9D81
.equ send_message_general_hook $9D84
.equ mark_last_hook_message_received $9D90
.equ set_own_priority $9D8A
.equ surrender_process_time $9D8D
.equ detach_self $9DA2
.equ strerror $9DC6
