.TH active_table_lookup(2),System Calls Manual,active_table_lookup(2)
.SH ADDRESS
$9DA5
.SH DESCRIPTION
- Returns information about the system active_processes_table
.SH ARGUMENTS
- .A -> index within active_processes_table to lookup
.SH RETURN VALUES
- .A -> result of lookup within active_processes_table

- .X -> index of active process within active_processes_table

- .Y -> currently active process

