.TH CLEAR(1),User Commands,CLEAR(1)

.SH NAME
clear - clear the terminal screen

.SH SYNOPSIS
clear

.SH DESCRIPTION
clear clears your terminal's screen if this is possible.

clear writes to the standard output.
You can redirect the standard output to a file (which prevents clear from actually clearing the screen),
and later cat the file to the screen, clearing it at that point.
