.TH FASTTERM(1),User Commands,FASTTERM(1)

.SH NAME
fastterm - fast-scrolling alternative terminal

.SH SYNOPSIS
fastterm [&]

.SH DESCRIPTION
fastterm is an alternative terminal for cx16os that implements faster scrolling routines than the cbm kernal by using VERA scrolling registers

.SH SEE ALSO
	splitterm(1), swapterm(1)