.TH FORTUNE(1),User Commands,FORTUNE(1)

.SH fortune - print a random adage

.SH SYNOPSIS
fortune

.SH DESCRIPTION
When called, fortune displays a randomly selected quotation or saying. The selection is based on the current time from the system clock.

.SH EXAMPLES

$ fortune
Talk is cheap. Show me the code. -- Linus Torvalds

$ fortune
640K ought to be enough for anybody.
