.TH mark_last_hook_message_received(2),System Calls Manual,mark_last_hook_message_received(2)
.SH ADDRESS
$9D90
.SH DESCRIPTION
If the calling process has a lock on hook .A, increment that hook's start_offset to point to the next message
.SH ARGUMENTS
- .A holds the bank number to affect
.SH RETURN VALUES
:  

- .A = 0 on success, non-zero on failure

