.TH parse_num(2),System Calls Manual,parse_num(2)
.SH ADDRESS
$9D15
.SH DESCRIPTION
- Parses the number pointed to by .AX

- Automatically checks number for `0x` or `$` prefix, in which case num is treated as base-16

- Otherwise base-10 is assumed

- Up to 32-bit values
.SH RETURN VALUES
- .AX = low 16 bits of the number parsed

- r0 = high 16 bits of the number parsed (zero for values <= $FFFF)

- .Y = 0 if the number was parsed successfully, non-zero otherwise

