.TH RANDOM(1),User Commands,RANDOM(1)

.SH NAME
random - generate random number

.SH SYNOPSIS

random

random SEED

random START END

random START STEP END

.SH DESCRIPTION
random  generates  a pseudo-random integer from a uniform distribution. The range (inclusive) depends on the arguments.

No arguments indicate a range of 0 to 32767 (inclusive).

If one argument is specified, the internal engine will be seeded with the  argument  for  future  invocations of random and no output will be produced.

Two arguments indicate a range from START to END (both START and END included).

Three arguments indicate a range from START to END with a spacing of STEP between possible outputs.

