.TH SCRIPTER(1),User Commands,SCRIPTER(1)

.SH scripter - specialized scripting language

.SH USAGE
scripter [OPTIONS]... FILE

.SH OPTIONS

-i: Run scripter in interactive mode

-e: Echo each command as it is run

-h: print a help message and exit

.SH PROGRAM EXECUTION
A scripter file consists of one or more of the following statements:

'$' : define a variable

'@' : run a asm routine

'-'/'!' : execute a program and wait for it to finish

'?' : conditional

'%' : goto

'>' : user input

'#' : line number label

'x' : exit, if in interactive mode (entered by using the `-i` flag)

.SH SYNTAX
`$` statement: define or set a variable

$variable_name [EXPRESSION]

`@` statement: run a asm routine

@routine_addr [REG=value]...

`-` / `!` statement: run an external program

-program_name [ARGS]

`?` statement: perform a statement conditionally

? CONDITION, $@-?% STATEMENT

`%` statement: goto a line number

% #LABEL_NAME

% LINE_NUMBER

`>` statement: get a line of input from the user

>$variable_to_write_input

`#` statement: set a label equal to the curr line number, to use in conjunction `%` statements

#label_name

.SH BUILT-IN VARIABLES
'.A' 8-bit value of A register after the last asm routine completed

'.C' 16-bit value of A/C register after the last asm routine completed

'.X' 16-bit value of X register after the last asm routine completed

'.AX' low bytes of A and X registers after the last asm routine completed

'.Y' 16-bit value of Y register after the last asm routine completed

'RETURN' return code of last external program executed

'.': current line number
