.TH set_stdin_read_mode(2),System Calls Manual,set_stdin_read_mode(2)
.SH ADDRESS
$9DBA
.SH DESCRIPTION
- Changes the behavior of getc(2)/fgetc(2) calls that read from the keyboard

- By default, input from the keyboard is buffered, waiting for a newline to be entered to return characters to a process.

- If a non-zero value is passed to this routine, os calls that read from the keyboard will now no longer buffer keyboard input and will return `0` if no chars are in the CBM keyboard buffer.

- If `0` is passed, the behavior will be restored to default.
.SH ARGUMENTS
- A -> byte whose zeroness signifies the keyboard input mode to use
.SH RETURN VALUES
- None

