.TH set_console_mode(2),System Calls Manual,set_console_mode(2)
.SH ADDRESS
$9DB7
.SH DESCRIPTION
- If there is no process with a hook on VERA register or the calling process has the hook, change the X16 terminal screen mode

- See ONLINE REFERENCE for the possible screen modes
.SH ARGUMENTS
- If .A <= $80, .A = the X16 terminal screen mode to use and if .X is a power of two >= 2, set the default VERA's VSCALE register value to .X

- If .A >= $80, define the terminal width and height for get_console_info(2) using .X and .Y
.SH RETURN VALUES
- A -> 0 on success, non-zero on failure to change the screen mode

