.TH wait_process(2),System Calls Manual,wait_process(2)
.SH ADDRESS
$9D5D
.SH DESCRIPTION
- Halts process execution until the process in .A exits

- Lowers process priority until routine is over (existing priority is restored)
.SH RETURN VALUES
- If process .A was alive when wait_process was first called, returns process return value in .A and 0 in .X

- Otherwise returns $FF in .X

